# Generated by Django 3.1.12 on 2022-05-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='subtitle_file',
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Start time')),
                ('end', models.TimeField(verbose_name='End time')),
                ('content', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('URL', 'Url'), ('VIDEO', 'Video Id'), ('PLAYLIST', 'Playlist Id'), ('JS', 'Js Script')], max_length=10, verbose_name='Link name')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='files.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue_identifier', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.TimeField(verbose_name='Start time')),
                ('end', models.TimeField(verbose_name='End time')),
                ('text', models.CharField(help_text='Subtitle text', max_length=300)),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='files.subtitle')),
            ],
        ),
    ]
